### ISSUE TITLE
[Doc]多端口监听Http/WebSocket的示例

### ISSUE THREAD

**Issue by jie295053415** [swoole-inc/report#27]
* 文档链接: `https://wiki.swoole.com/#/server/port`  
* 实际内容: //多监听一个TCP端口，对外开启TCP服务，并设置TCP服务器的回调
                  $tcp_server = $http_server->listen('0.0.0.0', 9999, SWOOLE_SOCK_UDP);
* 期望内容: //多监听一个TCP端口，对外开启TCP服务，并设置TCP服务器的回调
                  $tcp_server = $http_server->listen('0.0.0.0', 9999, SWOOLE_SOCK_TCP);

**Comment by sy-records** [comment]
已修改
