### ISSUE TITLE
[Case]

### ISSUE THREAD

**Issue by xwmhmily** [swoole-inc/report#28]
- 名称：建材猫
- 地点：广东佛山
- 联系方式：381345509@qq.com
- 业务场景：推送服务，NLP分词，短视频与直播 API，Swoole Tracker 性能分析

> 如果联系方式不方便公开、修改相关信息或不想出现在此列表，请单独发送至邮箱：[team@swoole.com](mailto:team@swoole.com)

**Comment by sy-records** [comment]
已添加。
