### ISSUE TITLE
[Doc] WebSocket\Server::pack 参数错误

### ISSUE THREAD

**Issue by NHZEX** [swoole-inc/report#30]
* 文档链接: `https://wiki.swoole.com/#/websocket_server?id=pack`  
* 实际内容: 
```
Swoole\WebSocket\Server::pack(string $data, int $opcode = 1, bool $finish = true, bool $mask = false): string
```  
* 期望内容: 
```
Swoole\WebSocket\Server::pack(string $data, int $opcode = WEBSOCKET_OPCODE_TEXT, int $flags = SWOOLE_WEBSOCKET_FLAG_FIN): string
```

目前定义：
https://github.com/swoole/swoole-src/blob/34b8eae76e8e82313f17347b004a142bed82fe21/swoole_websocket_server.cc#L71-L75

**Comment by sy-records** [comment]
修改自 https://github.com/swoole/swoole-src/pull/2937 ，Swoole版本 [v4.4.12](https://github.com/swoole/swoole-src/releases/tag/v4.4.12)

**Comment by sy-records** [comment]
增加了相关说明
