### ISSUE TITLE
Master 进程、Reactor 线程、Worker 进程、Task 进程、Manager 进程的区别与联系 介绍不全

### ISSUE THREAD

**Issue by bytehello** [swoole-inc/report#32]
* 文档链接: `https://wiki.swoole.com/#/learn?id=diff-process`  
* 实际内容: 标题是 **Master 进程、Reactor 线程、Worker 进程、Task 进程、Manager 进程的区别与联系**，但是下面的正文没有介绍到 Master 进程
* 期望内容:  正文内容可以描述一下 master 进程

**Comment by sy-records** [comment]
Master进程是一个多线程进程，看这个 进程 / 线程结构图 就懂了
![image](https://user-images.githubusercontent.com/33931153/90242652-fd3b4200-de5f-11ea-891b-9797748ed781.png)

**Comment by bytehello** [comment]
个人建议：如果能把张图片链接到这一章节的介绍里会更好

**Comment by sy-records** [comment]
加了链接
