### ISSUE TITLE
[Doc]补充sdebug的调试配置说明

### ISSUE THREAD

**Issue by yangmeishu** [swoole-inc/report#35]
* 文档链接: `https://wiki.swoole.com/#/question/install?id=%E5%AE%89%E8%A3%85xdebug`  
* 实际内容: 仅仅介绍安装完成，无配置方法，过于简单  
* 期望内容: 增加使用配置方法的介绍，具体文字如下：
区别于传统php下http的xdebug调试，swoole的sdebug调试有如下几点需要注意：

1. 需使用xdebug的cli调试方式作为调试入口，首先需配置好环境sdebug的环境变量,例：
`export XDEBUG_CONFIG="remote_enable=1 remote_mode=req remote_port=9000 remote_host=127.0.0.1 remote_connect_back=0" //具体值请按照实际项目并参考xdebug文档设置`
2.  需在启动swoole服务前设置好断点。也就意味着断点的取消需要要关闭swoole(终止整个实例)。可以如下思路解决，使用热更新组件，或自行写程序监控目录，当有文件变更时，终止kill实例后，再启动start实例。

**Comment by sy-records** [comment]
xdebug 的配置不是一两句话就可以说清楚的，既然要补就建议补充完整哈

**Comment by yangmeishu** [comment]
好的。期待swoole越做越好

**Comment by yangmeishu** [comment]
好的。期待swoole越做越好
