### ISSUE TITLE
[Doc] reload 参数 $only_reload_taskworkrer 中的 workrer 是不是写错了 。。

### ISSUE THREAD

**Issue by sdfjklmin** [swoole-inc/report#36]
* 文档链接: `https://wiki.swoole.com/#/server/methods?id=reload`  
* 实际内容: $only_reload_taskworkrer  
* 期望内容: $only_reload_taskworker

有强迫症，也不清楚是不是自己英语不过关 。。。

**Comment by sy-records** [comment]
嗯，是错了，已修正
