### ISSUE TITLE
[Doc]getElapsed 文档内写的传参有误。

### ISSUE THREAD

**Issue by chengze-cc** [swoole-inc/report#41]
* 文档链接: `https://wiki.swoole.com/#/coroutine/coroutine?id=getelapsed`  
* 实际内容: 
![image](https://user-images.githubusercontent.com/43336791/137875041-b7332dd2-7412-4f87-af19-7b3dfd85a6b6.png)
报错
![image](https://user-images.githubusercontent.com/43336791/137875375-1614999b-2b17-44fb-9024-b1ea0faac8e1.png)

* 期望内容: 去除数组形式，使用int即不会报错。
![image](https://user-images.githubusercontent.com/43336791/137875602-bfc1905c-ebfe-4121-b1d4-1d92563ce655.png)

**Comment by sy-records** [comment]
`[]` 表示可选
