### ISSUE TITLE
4.9.0-dev版本websocket握手环节失败

### ISSUE THREAD

**Issue by QinShangQs** [swoole-inc/report#42]
From wiki page: https://wiki.swoole.com/#/

---

前端websocket创建链接时出发onError和onClose事件，onClose.event.code=1006。但是使用telent协议可以建立链接。
后换成swoole 4.6.1版本，该问题自然消失。

**Comment by sy-records** [comment]
感谢反馈。

请使用 `release` 版本，`master` 为开发版，可能会有问题，正式发版时会修复问题。
