### ISSUE TITLE
https://wiki.swoole.com/#/coroutine_client/http2_client示例出错

### ISSUE THREAD

**Issue by ninx80** [swoole-inc/report#47]
文档链接: https://wiki.swoole.com/#/coroutine_client/http2_client
实际内容: 运行第一个示例结果：PHP Fatal error:  Uncaught Error: Class 'Swoole\Coroutine\Http2\Client' not found in /var/www/dockerwww/test/a9.php:8
Stack trace:
#0 {main}
  thrown in /var/www/dockerwww/test/a9.php on line 8
期望内容: 正常运行

**Comment by sy-records** [comment]
需要编译开启`http2`支持

https://wiki.swoole.com/#/environment?id=-enable-http2

**Comment by ninx80** [comment]
谢谢
