### ISSUE TITLE
文档实例有问题

### ISSUE THREAD

**Issue by ninx80** [swoole-inc/report#48]
文档链接: https://wiki.swoole.com/#/coroutine/notice?id=%e9%94%99%e8%af%af%e7%a4%ba%e4%be%8b-1
实际内容: http服务器运行过后，同时curl两个地址curl http://127.0.0.1:9501/a，curl http://127.0.0.1:9501/b，得到不是相同的结果，而是不同的
期望内容: 得到相同结果
疑问：利用异步方式开启http服务器，两个请求发出后，服务器是在同一个进程中开协程执行回调的吗？这个例子可能本来就有问题吧

**Comment by ninx80** [comment]
问题找到啦？
$server->set(["worker_num"=>1]);//加上这个就OK啦

**Comment by sy-records** [comment]
文档这里就是一个错误示例，标题就写清楚了。

**Comment by ninx80** [comment]
@sy-records 可能我描述有问题，
我电脑运行例子，没出现文档里预期的错误，所以才说有问题。。。不过也谢谢回复哈
这里我找了下原因：我电脑是两核，swoole默认的work_num是核数，所以默认情况下有两个进程来抢请求，两次请求分到了不同的进程中，不存在上下文问题了，所以我这里没有出现文档中描述的问题
建议加上$server->set(["worker_num"=>1]);这样才适用所有电脑，望采纳哦
