### ISSUE TITLE
使用Task::deliver查数据为先修改数据问题

### ISSUE THREAD

**Issue by lianran111** [swoole-inc/report#50]
From wiki page: https://wiki.swoole.com/#/start/start_task

---Task::deliver前修改了数据，在Task::deliver中查询数据时还是修改前的数据，这时该如何处理？

**Comment by sy-records** [comment]
Task::deliver 是什么？有这个方法？

**Comment by lianran111** [comment]
laravel+swoole有这个方法











在 2022-01-20 08:02:02，"沈唁" ***@***.***> 写道：

Task::deliver 是什么？有这个方法？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sy-records** [comment]
那你可能需要去问laravels那边了吧。
