### ISSUE TITLE
给个目录标记吧 这新文档好乱啊

### ISSUE THREAD

**Issue by isy-baicai** [swoole-inc/report#51]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/24862113/155922300-0031019d-ce6a-4439-bda7-95adcb950bff.png">
起码给个箭头标记一下里面还有子目录

**Comment by sy-records** [comment]
<img width="199" alt="image" src="https://user-images.githubusercontent.com/33931153/155926359-6930e435-6712-4dc7-9f8c-9be0f4b85d01.png">

点开不就有吗 你这是二次点击收起了

**Comment by isy-baicai** [comment]
知道 就是不明显 看着set() 想回去看核心api  点一次 核心api 就又收起来了
