### ISSUE TITLE
是我理解错误 还是哪个为准?

### ISSUE THREAD

**Issue by isy-baicai** [swoole-inc/report#52]
From wiki page: https://wiki.swoole.com/#/coroutine/coroutine?id=set

---
<img width="904" alt="image" src="https://user-images.githubusercontent.com/24862113/155937812-8b31ca54-8e26-4ebf-b7bd-301590739764.png">
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/24862113/155937843-a470c3d6-e3ab-4463-b884-529ad8fbc83a.png">

**Comment by sy-records** [comment]
`Coroutine::set`的时候是设置C栈应用层，这里还有个别名是`c_stack_size`，文档已修正。
