### ISSUE TITLE
文档的大小写规范一下吧 

### ISSUE THREAD

**Issue by isy-baicai** [swoole-inc/report#53]
From wiki page: https://wiki.swoole.com/#/coroutine/coroutine

---
<img width="679" alt="image" src="https://user-images.githubusercontent.com/24862113/156150652-1e3a904b-821e-454f-bc31-8a21c034e261.png">
虽然php不区分类的大小写 但是一个优秀的项目 还在要注意一下这点吧

**Comment by sy-records** [comment]
已修复
